# infra/jenkins_playbook.yml
---
- name: Provision Jenkins server
  hosts: jenkins
  become: yes
  gather_facts: yes
  vars:
    jenkins_hostname: jenkins.example.com

  tasks:
    - name: Install Jenkins dependencies
      yum:
        name: ['java-1.8.0-openjdk-devel']
        state: latest

    - name: Enable Jenkins repository
      shell: "curl --silent --location http://pkg.jenkins.io/redhat-stable/jenkins.io.key | sudo rpm --import -"

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        enabled: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
      notify: Start Jenkins

  handlers:
    - name: Start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes
