# infra/jenkins_playbook.yml
---
- name: Provision Jenkins server
  hosts: jenkins_instance
  become: yes
  gather_facts: yes
  vars:
    jenkins_hostname: jenkins.example.com

  tasks:
    - name: Install Jenkins dependencies
      yum:
        name: ['java-1.8.0-openjdk-devel']
        state: latest
    
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - ca-certificates
        state: latest

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      ansible.builtin.yum_repository:
        name: jenkins
        description: Jenkins repository
        baseurl: https://pkg.jenkins.io/redhat
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        gpgcheck: no

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
      notify: Start Jenkins

  handlers:
    - name: Start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes
